### ISSUE TITLE
Nice work！！ And when can we get datasets?

### ISSUE THREAD

**Issue by BlueBlueFF** [ucas-vg/TinyBenchmark#1]

**Comment by yinglang** [comment]
Thanks for your interest, we are trying to apply for holding a competition of "Tiny Person Detection" at ECCV2020 Workshop.So annotations of training set and all images will be release in **January 2020**. And if the proposal is accepted by ECCV2020 Workshop, the annotations of testing set will be release after the competition finished(about **March 2020**). @BlueBlueFF
