### ISSUE TITLE
how to set configs?

### ISSUE THREAD

**Issue by hlh199603** [ucas-vg/TinyBenchmark#11]
CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=$NGPUS tools/train_test_net.py --config ${config_path}
how to set ''--config ${config_path}''

**Comment by yinglang** [comment]
''--config ${config_path}'' mean use config file to train, just like 
"--config configs/TinyPerson/FPN/baseline1/e2e_faster_rcnn_R_50_FPN_1x_cocostyle_baseline1.yaml"
