### ISSUE TITLE
gpu problem

### ISSUE THREAD

**Issue by hlh199603** [ucas-vg/TinyBenchmark#12]
AssertionError: NUM_GPU is not equal to visible GPU count 2 vs 1.
i just have one gpu, how to solve this problem? thankyou

**Comment by yinglang** [comment]
Just change SOLVER.NUM_GPU to 1 in your running config file. just like [maskrcnn_benchmark](https://github.com/facebookresearch/maskrcnn-benchmark#single-gpu-training) said, If you experience out-of-memory errors, you can reduce the global batch size. But this means that you'll also need to change the learning rate, the number of iterations and the learning rate schedule.
