### ISSUE TITLE
pretrain-model

### ISSUE THREAD

**Issue by hlh199603** [ucas-vg/TinyBenchmark#13]
FileNotFoundError: [Errno 2] No such file or directory: '/home/hui/params/pretrained_model/ImageNetPretrained/MSRA/R-50.pkl'
can you share me a pretrain model?

**Comment by yinglang** [comment]
yes, I will upload these pretrain weight this evening. For ImageNetPretrained/MSRA/R-50.pkl, you can just change setting to 
` WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"`
