### ISSUE TITLE
some training question

### ISSUE THREAD

**Issue by Pluto1314** [ucas-vg/TinyBenchmark#17]
Hi！I'm sorry to disturb you!
In your paper, you used the coco dataset to pretrain and SM to the tinyperson dataset. How can I get the coco pretrained weight of my own dataset? And I still don't know how to use my own dataset to train?
I‘m looking forward to your reply! Thank you!

**Comment by yinglang** [comment]
there are some steps you may need:
1. turn the annotations of your dataset to COCO format;
2. change config file like [config file in this directory](https://github.com/ucas-vg/TinyBenchmark/tree/master/tiny_benchmark/configs/TinyCOCO), you must change 
DATALOADER.SCALE_MATCH.TARGET_ANNO_FILE
3. if you use MSM(monotonicity scale match), you may need [instances_simple_merge2014.json](https://github.com/ucas-vg/TinyBenchmark/tree/master/tiny_benchmark/configs/TinyCOCO), and change DATALOADER.SCALE_MATCH. SOURCE_ANNO_FILE in config file.
4. and you may need change lr policy in config file adapted for your dataset.
5. train to get your pretrain weight.

that's may be all thing I can consider so far, if you have any other problem, please tell us, and we will try to help.
And For more, we are consider to add an example that train on other dataset with scale match the next two days. which may can help you.

**Comment by Pluto1314** [comment]
Thank you very much. I think it will help me a lot!
