### ISSUE TITLE
A problem when I run evaluate_tiny.py !!!

### ISSUE THREAD

**Issue by zhaowujie** [ucas-vg/TinyBenchmark#18]
When I run TinyBenchmark/tiny_benchmark/MyPackage/tools/evaluate/ #evaluate_tiny.py, I got an error:

```
/media/hp208/4t/zhaoxingjie/project_graduation/TinyBenchmark/venv/bin/python /media/hp208/4t/zhaoxingjie/project_graduation/TinyBenchmark/tiny_benchmark/MyPackage/tools/evaluate/evaluate_tiny.py
Traceback (most recent call last):
  File "/media/hp208/4t/zhaoxingjie/project_graduation/TinyBenchmark/tiny_benchmark/MyPackage/tools/evaluate/evaluate_tiny.py", line 14, in <module>
    from MyPackage.visulize.plot_train_log import parse_log, replace_key
ImportError: No module named 'MyPackage.visulize'
```

Anyone meet the same problem?

**Comment by yinglang** [comment]
Thanks to your. we have fixed this problem, you can add --detail flag to avoid it, such as `python evaluate_tiny.py --res ~/results/bbox_merge_nms0.5.json --gt ~/dataset/tiny_set_test_all.json --detail`. For evaluate MR is slowly, you can specified "--metric ap" to speed up.

**Comment by zhaowujie** [comment]
Thank you very much!
