### ISSUE TITLE
instances_simple_merge2017.json

### ISSUE THREAD

**Issue by Pluto1314** [ucas-vg/TinyBenchmark#20]
Hi! Can you provide instances_ simple_ merge2017.json?
At the same time, how do I get merge2017.json or merge2014.json?

**Comment by yinglang** [comment]
we only merge coco2014 to a single son file and you can get [here](https://github.com/ucas-vg/TinyBenchmark/tree/master/tiny_benchmark/configs/TinyCOCO). But in my observation, there are just little difference between 2014 and 2017. For scale matching, 2014 will be almost same as 2017.

**Comment by Pluto1314** [comment]
好的，谢谢你的回复。还有就是想问一下，这个merge指的是直接将train和val的json加在一起对吧，比如将train和val的annotation都放在一个annotation里面，其他字典类似。请问下是这个意思吗，我可以尝试自己制作一个merge2017。
