### ISSUE TITLE
some questions about my results

### ISSUE THREAD

**Issue by ly19965** [ucas-vg/TinyBenchmark#25]

**Comment by yinglang** [comment]
Have you solved this problem? In our experiment, For adaptive retinanet, we try train on different GPU(1080Ti, 2080ti) and get different result, which we do not find the reason. And sometimes set NUM_GPU to 1 will reproduce the performance of adaptive retinanet if NUM_GPU set to 2 not. But adaptive FPN have no such problem. And your may try early stop while training which means the final result may be not the best.

**Comment by yinglang** [comment]
And can you provide your GPU version and any other concerned software version you think may have some affect?
