### ISSUE TITLE
scale match

### ISSUE THREAD

**Issue by Lily19970207** [ucas-vg/TinyBenchmark#26]
DATASETS:
  **TRAIN: ("coco_2014_train", "coco_2014_valminusminival", "coco_2014_minival")
  TEST: ("coco_2014_minival",)**
DATALOADER:
  SIZE_DIVISIBILITY: 32
  USE_MORE_DA: 4
  USE_SCALE_MATCH: True
  `SCALE_MATCH:`
    TYPE: 'MonotonicityScaleMatch'
    SOURCE_ANNO_FILE: **'${YOUR_DATASET_DIR}/coco/annotations/instances_simple_merge2014.json'**
    TARGET_ANNO_FILE: '${YOUR_DATASET_DIR}/tiny_set/erase_with_uncertain_dataset/annotations/corner/task/tiny_set_train_sw640_sh512_all.json'
    BINS: 100
    DEFAULT_SCALE: 0.25
    SCALE_RANGE: (0.1, 1.)
    OUT_SCALE_DEAL: 'clip'、

Hello,I want use scale match ,can I know source_anno_file is the annotation of train_set?Or the annotation of train_set still adopts the original annotation of coco dataset

**Comment by yinglang** [comment]
SOURCE_ANNO_FILE is the retrain dataset, in here means COCO, [this page](https://github.com/ucas-vg/TinyBenchmark/tree/master/tiny_benchmark/configs/TinyCOCO) may help you!
