### ISSUE TITLE
lack of a file of json

### ISSUE THREAD

**Issue by dyx118186878** [ucas-vg/TinyBenchmark#27]
when i train with the config file in TINYPERSON/FPN/BASELINE1 the e2e_faster_rcnn_R_50_FPN_1x_cocostyle_baseline1.yaml

it works for a while，later it stop saying：
No such file or directory: '/media/ubuntu/0000BFD200076E00/U-net/TinyBenchmark-master/dataset/tiny_set/annotations/corner/task/tiny_set_test_sw640_sh512_all.json'

i check the folder ，it does lack the file ，only/tiny_set_train_sw640_sh512_all.json' why

**Comment by yinglang** [comment]
I think this question is same as [issuses/16](https://github.com/ucas-vg/TinyBenchmark/issues/16), maybe the answer can help you.
