### ISSUE TITLE
How to test using pre-trained weights and my test images

### ISSUE THREAD

**Issue by abhinavchawla13** [ucas-vg/TinyBenchmark#29]
Hey, firstly, I'm new to maskrcnn. I'm trying to used pre-trained weights to infer tiny persons on an image, but I am not sure how to do it. 
I tried to follow [demo](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/demo/Mask_R-CNN_demo.ipynb), but it uses `coco_demo.run_on_opencv_image(image)` which I'm confused how to adapt for the [inference](https://github.com/ucas-vg/TinyBenchmark/blob/f1ff12b6695856e69777019872b5affebcd76923/tiny_benchmark/maskrcnn_benchmark/engine/inference.py#L54) used in [test_net.py](https://github.com/ucas-vg/TinyBenchmark/blob/master/tiny_benchmark/tools/test_net.py)

What I have tried:
1. Testing on `coco_val2014` dataset. I downloaded it, and put it inside `dataset/coco` along with `instances_minival2014.json` file. 
1.1 I added a new config in `path_config.py` with:
```
coco_val_test: {
   img_dir: #path to coco dataset images,
   ann_dir: #path to `instances_minival2014`
}
```
1.2 Updated this [config file](https://github.com/ucas-vg/TinyBenchmark/blob/master/tiny_benchmark/configs/TinyPerson/FPN/baseline1/e2e_faster_rcnn_R_50_FPN_1x_cocostyle_baseline1.yaml) to include `coco_val_test` under test, and updated `WEIGHT` to `#path to params/model_only_e2e_faster_rcnn_R_50_FPN_1x.pth` downloaded from [Drive](https://drive.google.com/drive/folders/1CXlwz4enGUfR-39-c75dqtrI35UWlaiz)
1.3 Ran `CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=$NGPUS tools/test_net.py --config ${config_path}`

It ran through and generated a bbox.json. I tried to put these boxes on an image, but these boxes didn't make any sense (incorrect drawings). 

Similarly, I tried making my own version of `instances_minival2014.json` with only 1 image. It also ran the `test_net.py` but the output bbox is not coming correct. 

Looks like this:
![image](https://user-images.githubusercontent.com/10625526/83919860-85f37e80-a749-11ea-8c04-0999e6107f0a.png)

Can some one please help me set it up? Any help will be appreciated!

**Comment by NgDung28** [comment]
![result_bb_V0000_I0001120](https://user-images.githubusercontent.com/18476960/84747254-3894ce00-afe1-11ea-892e-9bb23c946400.jpg)
First, I tried testing one image with pretrained model and the result was very poor like yours. Then I trained new model using train_test_net.py and the result is better.
![result_1_bb_V0000_I0001120](https://user-images.githubusercontent.com/18476960/84747641-b8229d00-afe1-11ea-8425-54c9a9ce7313.jpg)

**Comment by dyx118186878** [comment]
@NgDung28 hi , which yaml  did you choose to train, when i use my trained model ,there is no boxes in the frame, can you provide your prediction demo, i am new with the code thanks a lot.

**Comment by abhinavchawla13** [comment]
@NgDung28, yes I did the same thing by re-training using train_test_net.py on `tiny_set_corner_sw640_sh512_erase_with_uncertain_train_all_coco`
 dataset and was able to then infer much better.

![image](https://user-images.githubusercontent.com/10625526/84802470-a4ba0680-afce-11ea-99a8-8676f1996349.png)
![image](https://user-images.githubusercontent.com/10625526/84802507-b6031300-afce-11ea-9c26-dd7f82ffdb9b.png)

Did you train your network on the same dataset as well or a different one?

My .yaml had this:
```
DATASETS:
    TRAIN: ("tiny_set_corner_sw640_sh512_erase_with_uncertain_train_all_coco",)
    TEST: ("coco_my_dummy",) #my own testing dataset 
```

**Comment by abhinavchawla13** [comment]
@dyx118186878, I'll tell you what I did to train it:
After like 100 tries, I found this to work for me. I used this [config file](https://github.com/ucas-vg/TinyBenchmark/blob/master/tiny_benchmark/configs/TinyPerson/retina/baseline2/retina_R_50_FPN_1x_baseline2_lrfpn_smb4coco.yaml) and updated:
```
DATASETS:
    TRAIN: ("tiny_set_corner_sw640_sh512_erase_with_uncertain_train_all_coco",)
    TEST: ("coco_my_dummy",) #my own testing dataset 
```
Ensure you have download the pretrained weights from the documentation links, so the initial weights don't give error here:
```
WEIGHT: "../params/adap_retina_sm_tinyperson_b4/model_only_model_final.pth"
```
When you run this, you would get some errors on the training set, as it will few json files missing inside the `datasets/tiny_set/erase_with_uncertain_data/annotations` for the test. I just re-used (copy) the training json and rename it to train, as testing and training data is same right now (official test annotations are not out yet)

I might be missing a few things here, but that's more or less what I did to get it to train (took my 12 hours on single GPU machine btw)

For testing, I created a new object inside `tiny_benchmark/maskrcnn_benchmark/config/paths_catalog.py`:
```
"coco_my_dummy": {
    "img_dir": "dummy/images" #refers inside dataset folder,
    "ann_file": "dummy_all.json" #based on coco json format
}
```
Since I only used it for testing, I didn't need to add bbox info in dummy_all.json, it just looked like:
```
{
    "images": [
          {
                "id": 1,
                "filename": "1.jpg",
                "height": 1920,
                "width": 1080
          },
         categories: [
               {
                      "supercateogry": "person",
                      "id": 1,
                      "name": "person"
                }
         ]
    ]
}
```

Lastly after training, you can find the model weights file (.pth) in outputs. Use that to update config.yaml to use this as new weights. And then you can run test_net.py with the config value to see bbox.json. 

You can use matplotlib to draw boxes on the image later (just make sure match bbox data with the image id).

I hope this helps, I am new to this myself and struggled to get this set up. **Pretty sure** there is a better way to do it, I just don't know it.

**Comment by NgDung28** [comment]
@dyx118186878 Yes, some pretrained model return no boxes. So I retrained it using retina_R_50_FPN_1x_baseline2_lrfpn_msmb4coco.yaml, what I do is similar to @abhinavchawla13. Howerver, because I trained with this tiny dataset so I didn't work well with my test images. I will try training with my own dataset later.

**Comment by abhinavchawla13** [comment]
I will close the issue as I think I fould a way around it (re-train the weights)
