### ISSUE TITLE
Question about extra datasets image-level scaling in pre-training process

### ISSUE THREAD

**Issue by 422301949** [ucas-vg/TinyBenchmark#30]
I have some questions about extra datasets image-level scaling. After image-level scaling, the size of images in COCO dataset are various. How to solve the problem of image scale difference in the pre-training process.

**Comment by yinglang** [comment]
if batch_per_gpu > 1, we adopt maskrccnn_benchmark [default padding strategy](https://github.com/ucas-vg/TinyBenchmark/blob/master/tiny_benchmark/maskrcnn_benchmark/structures/image_list.py):


`
        batch_shape = (len(tensors),) + max_size
        batched_imgs = tensors[0].new(*batch_shape).zero_()
        for img, pad_img in zip(tensors, batched_imgs):
            pad_img[: img.shape[0], : img.shape[1], : img.shape[2]].copy_(img)
`

**Comment by 422301949** [comment]
> if batch_per_gpu > 1, we adopt maskrccnn_benchmark [default padding strategy](https://github.com/ucas-vg/TinyBenchmark/blob/master/tiny_benchmark/maskrcnn_benchmark/structures/image_list.py):
> 
> ```python
>         batch_shape = (len(tensors),) + max_size
>         batched_imgs = tensors[0].new(*batch_shape).zero_()
>         for img, pad_img in zip(tensors, batched_imgs):
>             pad_img[: img.shape[0], : img.shape[1], : img.shape[2]].copy_(img)
> ```

Thanks for your replay. Large differences in image scales may cause the network to be sensitive to the upper left corner of the image and under-fit to the lower right corner.

**Comment by 422301949** [comment]
> if batch_per_gpu > 1, we adopt maskrccnn_benchmark [default padding strategy](https://github.com/ucas-vg/TinyBenchmark/blob/master/tiny_benchmark/maskrcnn_benchmark/structures/image_list.py):
> 
> ```python
>         batch_shape = (len(tensors),) + max_size
>         batched_imgs = tensors[0].new(*batch_shape).zero_()
>         for img, pad_img in zip(tensors, batched_imgs):
>             pad_img[: img.shape[0], : img.shape[1], : img.shape[2]].copy_(img)
> ```

thanks for you reply!
