### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by GuangqianGuo** [ucas-vg/TinyBenchmark#39]
hi~, firstly, I think it is a good job.
However, when I run your code , I got the following error:
`ImportError: /home/ubuntub/Guo/TinyBenchmark-master/tiny_benchmark/maskrcnn_benchmark/_C.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIN3c108BFloat16EEEPKNS_6detail12TypeMetaDataEv`

But I have done ` python setup.py build develop` following your instructions. 
I am sincerely looking forword to your reply.
Thanks!

**Comment by yinglang** [comment]
For using conda install instead of pip, the problem gone. 

And we close this issue.
