### ISSUE TITLE
when can we get the dataset and the code

### ISSUE THREAD

**Issue by dyx118186878** [ucas-vg/TinyBenchmark#4]
i am very interested in your method ，when can you provide the code ，i cannot wait to study for it  . thanks a lot .

**Comment by yanchangqin** [comment]
Me too，waiting for the dataset and code!!

**Comment by yinglang** [comment]
sorry for late to release because of some reasons , the dataset (images and annotations of train set ) has released just now , the code and the website for evaluating model on test set will try to release this week .

**Comment by dadaligoudan** [comment]
> 
> 
> sorry for late to release because of some reasons , the dataset (images and annotations of train set ) has released just now , the code and the website for evaluating model on test set will try to release this week .

hello, seems you only realeased the images and annotations of train set , the images of the test set. Would you please realease the annotations of the test set to us? Thanks a lot.

**Comment by yinglang** [comment]
yes, we only realeased the images and annotations of train set , the images of the test set. Cause this dataset are used for [ECCVW2020 challenge](https://rlq-tod.github.io/challenge1.html), the annotation for test set will not release until the challenge finished. if you want to evaluate your method on test set, you can upload result to [Codalab TOD challenge](https://competitions.codalab.org/competitions/24551#results) just as [this section](https://github.com/ucas-vg/TinyBenchmark/blob/master/tiny_benchmark/README.md#evaluation-)  told.
