### ISSUE TITLE
How to evaluate my results on the test set

### ISSUE THREAD

**Issue by qiqcheng** [ucas-vg/TinyBenchmark#40]
How to evaluate my results on the test set？

**Comment by yinglang** [comment]
Sorry for reply late, there are two way to evaluate,:
1. if you use our tiny_benchmark, you can just change MERGE_GT_FILE as your gt file path downlaod from Google Driver or BaiduYun
![image](https://user-images.githubusercontent.com/9081484/95549902-a787ae00-0a3a-11eb-9662-4cc29e6d3366.png)
and re-run train_test.py script with same config file, the evaluation will start automatic.
2. if you use other code to generate result, you can use script tiny_benchamrk/MyPackage/tools/evaluate_tiny.py to evalute, for example
`
python evaluate_tiny.py --res ~/results/your_result.json --gt ~/dataset/tiny_set_test_all.json --detail
` 
and the mr evaluation is time-cost, you can specified --metric to evaluate AP only
`
python evaluate_tiny.py --res ~/results/your_result.json --gt ~/dataset/tiny_set_test_all.json --detail --metric 'ap'
`

and your_result.json should satisfy such format
```
[{'image_id': 793, 'category_id': 1, 'bbox': [0.0, 0.0, 1.0, 1.0], 'score': 0.009999999776482582}, 
{'image_id': 793, 'category_id': 1, 'bbox': [590.0, 0.0, 1.0, 1.0], 'score': 0.009999999776482582},
......
{'image_id': 795, 'category_id': 1, 'bbox': [1180.0, 0.0, 1.0, 1.0], 'score': 0.009999999776482582}]
```

**Comment by qiqcheng** [comment]
Thanks for your reply, there is no test annotation file in the data I downloaded before, now I know how to do it.
