### ISSUE TITLE
IOD

### ISSUE THREAD

**Issue by Pluto1314** [ucas-vg/TinyBenchmark#42]
![image](https://user-images.githubusercontent.com/47765770/97172127-85778500-17c9-11eb-8761-26699e7d0173.png)

Hello, does this result of your paper use IOD?

**Comment by yinglang** [comment]
it is same as [#41 ](https://github.com/ucas-vg/TinyBenchmark/issues/41).
yes, both old and new evaluation were applied IOD. the difference between them is different division of 'ignore area'.
