### ISSUE TITLE
test conf thres

### ISSUE THREAD

**Issue by Pluto1314** [ucas-vg/TinyBenchmark#44]
Hi, sorry to disturb you. 
What is the confidence threshold used in the test time? I did not see this setting in the .yaml file.
may be 0.01 or 0.001 ?

**Comment by yinglang** [comment]
All other config param not specified in config file can be seen in [maskrcnn_benchmark/config/defaults.py](https://github.com/ucas-vg/TinyBenchmark/blob/master/tiny_benchmark/maskrcnn_benchmark/config/defaults.py) in maskrcnn_benchmark based code. confidence threshold I beeped it same as origin code, 0.05 if remember correctly.

**Comment by Pluto1314** [comment]
Thank you very much, I see it in the dedaults.py file.
![image](https://user-images.githubusercontent.com/47765770/100563525-8be1ab00-32f9-11eb-977c-2ca319b5f8ca.png)
