### ISSUE TITLE
Why the max iter is set to 19236? How is it calculated?

### ISSUE THREAD

**Issue by wenjie710** [ucas-vg/TinyBenchmark#45]
Hi, I am confused about the setting. The number of image id is 8256, why the max iteration is set to 19236? Do we only need to train around 2 epoch ? how is 19236  caculated?

**Comment by yinglang** [comment]
1. although there are 8256 images in TinyPerson corner540x512 dataset, but there are many pure backgroud image(which have no any object in the image) in corner dataset for the object is too tiny to the whole image.
2. For the current major detector, pure backgroud image will not  participate in training process. so the 19236 is actrually about 12 epochs as normal 1x schedule defined in detectetion.
