### ISSUE TITLE
some question about tiny cityperson

### ISSUE THREAD

**Issue by Pluto1314** [ucas-vg/TinyBenchmark#46]
Hi, sorry to disturb you.
Could you tell me more details about training tiny citypersons?

**1. Used several categories**

There are four categories in Citypersons paper. How many categories did you use?
![image](https://user-images.githubusercontent.com/47765770/101432289-8ca2be80-3943-11eb-9f27-d97892b5aeb9.png)

**2. How to get the data in paths_catalog.py?**

I only know that tiny citypersons downsample cityperson to 4*4. But I don’t know if tiny citypersons also use the same crop and erasure as tinyperson. Or you can provide training and val data for tiny citypersons, thank you very much!
![image](https://user-images.githubusercontent.com/47765770/101432716-531e8300-3944-11eb-81bf-c7f2fe6671de.png)

**Comment by yinglang** [comment]
We use the annotation of CityPersons as general pedestrain detection did, which only "pedestrian" will be used.
you can download images and labels from citypersons website. And I will upload them too, which maybe takes some hours.

**Comment by yinglang** [comment]
I have upload tiny citypersons to Baidu Pan [here](https://github.com/ucas-vg/TinyBenchmark/blob/master/README.md#tiny-citypersons)

**Comment by Pluto1314** [comment]
Thank you very much, I will close this issue~
