### ISSUE TITLE
AP gap between TinyBenchmark and MMDetection

### ISSUE THREAD

**Issue by Chasel-Tsui** [ucas-vg/TinyBenchmark#49]
Hello, I appreciate your work and I tried to re-implement the baseline with FPN on MMDetection,  but the AP50tiny metric is extremely low (only about 7%) with the same settings on MMDetection. Has anyone ever come across the same problem and could you please give me some suggestions about the parameter setting of models or some other details?

**Comment by yinglang** [comment]
We are not sure about the detail of problem you meet cause there are too less infomation. But we will try to transfer code in TinyBenchmark to mmdetection recently. There may be results in the next few days.  Maybe we can talk at that time. Thanks for your attention.

**Comment by yinglang** [comment]
The mmdetection version of part of TinyBenchmark has been released to [https://github.com/ucas-vg/TOV_mmdetection](https://github.com/ucas-vg/TOV_mmdetection)， which may help you somwhat.

**Comment by Chasel-Tsui** [comment]
Thank you very much!!!

**Comment by Fly-dream12** [comment]
Will you add that how to train on TinyPerson with scale match on COCO? @yinglang

**Comment by yinglang** [comment]
yes, we will.

**Comment by yinglang** [comment]
Training on TinyPerson with SM/MSM on COCO has been add on [https://github.com/ucas-vg/TOV_mmdetection](https://github.com/ucas-vg/TOV_mmdetection).

**Comment by Hshuqin** [comment]
> Hello, I appreciate your work and I tried to re-implement the baseline with FPN on MMDetection, but the AP50tiny metric is extremely low (only about 7%) with the same settings on MMDetection. Has anyone ever come across the same problem and could you please give me some suggestions about the parameter setting of models or some other details?

Hello, I am also recently running tiny person this dataset,  can add WeChat to discuss it？
