### ISSUE TITLE
How is  your_result.json file calculated?

### ISSUE THREAD

**Issue by Chadhui** [ucas-vg/TinyBenchmark#50]

**Comment by yinglang** [comment]
It's reuslt file which record all detection results on test set as [here](https://github.com/ucas-vg/TinyBenchmark/tree/master/tiny_benchmark#evaluation-) said.

Noramlly the output result of [MaskRCNN Benchmark](https://github.com/facebookresearch/maskrcnn-benchmark) and [mmdetection](https://github.com/open-mmlab/mmdetection) is same as the format.

**Comment by Chadhui** [comment]
How can yolov5 get the same type of result.json file?

**Comment by yinglang** [comment]
yes, it should be same.
